name: build-linux

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSL https://bun.sh/install | bash
          mkdir dist
          ~/.bun/bin/bun build src/main.ts --compile --outfile linux
          mv linux dist
          cd dist
          zip linux.zip linux
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/linux.zip